name: Vetted
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+27

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_signin_button: ^2.0.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.4.1
  cherry_toast: ^1.13.0
  http: ^1.4.0
  http_parser: ^4.1.2
  loading_animation_widget: ^1.3.0
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  get: ^4.7.2
  google_sign_in: ^7.1.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.1 
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  camera: 0.10.5+9
  permission_handler: ^11.3.0
  onesignal_flutter: ^5.3.4
  image_picker: ^1.2.0
  font_awesome_flutter: ^10.9.1
  socket_io_client: ^3.1.2
  scrollable_positioned_list: ^0.3.8
  chewie: ^1.13.0
  audio_waveforms: ^1.3.0
  video_compress: ^3.1.4
  video_thumbnail: ^0.5.6
  visibility_detector: ^0.4.0+2
  flutter_polls: ^0.1.6
  url_launcher: ^6.3.2
  app_links: ^6.4.1
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: 2.5.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/v_logo_1.png
    - assets/images/v_logo_2.png
    - assets/images/background_1.png
    - assets/images/otp_illustration.png
    - assets/images/icons/anonymous.png  
    - assets/images/icons/screenshot.png  
    - assets/images/icons/verified.png  
    - assets/images/icons/posts.png  
    - assets/images/icons/search.png  
    - assets/images/icons/alerts.png
    - assets/images/icons/run_background.png
    - assets/images/icons/check_criminal.png
    - assets/images/icons/Search_1.png
    - assets/images/icons/look_up.png
    - assets/images/icons/search.png
    - assets/images/icons/find_social.png
    - assets/images/icons/name_popup.png
    - assets/images/notifications_illustration.png
    - assets/images/birthday_popup.png
    - assets/images/map_mock.png
    - assets/images/map_1.png
    - assets/images/selfie_icon.png
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/user3.png
    - assets/images/user4.png
    - assets/images/user5.png
    - assets/images/user6.png
    - assets/images/logo_black.png
    - assets/images/icons/edit.png
    - assets/images/icons/arrow.png
    - assets/images/icons/send.png
    - assets/images/icons/nav_active.png
    - assets/images/icons/nav_inactive1.png
    - assets/images/icons/nav_inactive2.png
    - assets/images/icons/nav_inactive3.png
    - assets/images/icons/nav_inactive4.png
    - assets/images/sample_post.png
    - assets/images/icons/woman.png
    - assets/images/icons/meme.png
    - assets/images/icons/poll.png
    - assets/images/icons/audio.png
    - assets/images/map_sample.png
    - assets/images/icons/nav_active1.png
    - assets/images/icons/nav_active2.png
    - assets/images/icons/nav_active3.png
    - assets/images/record.png
    - assets/images/invite_bg.png
    - assets/images/invite_people.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_black.png"
